using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using MerchApp.Models;
using MerchApp.Services;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MerchApp.ViewModels
{
    public partial class ItemsViewModel : ObservableObject
    {
        private readonly ISharePointService _sharePointService;
        private readonly ICartService _cartService;
        private readonly ISessionContext _session;

        // -------------------------------------------------------------------------
        // Observable properties
        // -------------------------------------------------------------------------
        [ObservableProperty]
        private ObservableCollection<Item> _items = new();

        [ObservableProperty]
        private ObservableCollection<Item> _filteredItems = new();

        [ObservableProperty]
        private bool _isBusy;

        [ObservableProperty]
        private string _errorMessage = string.Empty;

        [ObservableProperty]
        private bool _hasError;

        [ObservableProperty]
        private string _searchQuery = string.Empty;

        [ObservableProperty]
        private bool _showOnlyAvailable;

        [ObservableProperty]
        private int _cartCount = 0;


        public ItemsViewModel(ISharePointService sharePointService, ICartService cartService, ISessionContext session)
        {
            _sharePointService = sharePointService;
            _cartService = cartService;
            _session = session;

            // react to cart changes to update badge count
            _cartService.CartChanged += (_, _) => _cartCount = _cartService.TotalQuantity;
        }


        // -------------------------------------------------------------------------
        // Commands
        // -------------------------------------------------------------------------

        [RelayCommand]
        private async Task LoadItemsAsync()
        {
            if (IsBusy) return;

            IsBusy = true;
            HasError = false;
            ErrorMessage = string.Empty;

            try
            {
                var items = await _sharePointService.GetItemsAsync();

                Items.Clear();
                foreach(var item in items)
                {
                    Items.Add(item);
                }

                ApplyFilter();
            }
            catch (Exception ex)
            {
                HasError = true;
                ErrorMessage = ex.Message;
            }
            finally
            {
                IsBusy = false;
            }
        }

        [RelayCommand]
        private void AddToCart(Item item)
        {
            if(item == null || !item.IsAvailable) return;

            _cartService.AddItem(item);
        }

        [RelayCommand]
        private void RemoveFromCart(Item item)
        {
            if (item == null) return;

            _cartService.RemoveItem(item);
        }

        [RelayCommand]
        private void SetItemQuantity((Item item, int quantity) args)
        {
            _cartService.SetQuantity(args.item, args.quantity);
        }

        [RelayCommand]
        private void Search(string query)
        {
            SearchQuery = query;
            ApplyFilter();
        }

        [RelayCommand]
        private void ToggleAvailableOnly()
        {
            ShowOnlyAvailable = !ShowOnlyAvailable;
            ApplyFilter();
        }

        /// <summary>
        /// Returns current quantity of an item in the cart.
        /// Used by the View to show +/- controls.
        /// </summary>
        public int GetCartQuantity(Item item) =>
            _cartService.GetQuantity(item);

        /// <summary>
        /// Returns true if the item is in the cart.
        /// </summary>
        public bool IsInCart(Item item) =>
            _cartService.Contains(item);

        private void ApplyFilter()
        {
            var filtered = Items.AsEnumerable();

            if (!string.IsNullOrWhiteSpace(SearchQuery))
                filtered = filtered.Where(i =>
                    i.Title.Contains(SearchQuery, StringComparison.OrdinalIgnoreCase));

            if (ShowOnlyAvailable)
                filtered = filtered.Where(i => i.IsAvailable);

            FilteredItems.Clear();
            foreach (var item in filtered)
                FilteredItems.Add(item);
        }

        // Called when SearchQuery property changes (auto-generated by ObservableProperty)
        partial void OnSearchQueryChanged(string value) => ApplyFilter();
        partial void OnShowOnlyAvailableChanged(bool value) => ApplyFilter();
    }
}
